### ISSUE TITLE
パラメータ調整用GUIがほしい

### ISSUE THREAD

**Issue by okadatech** [Setouchi-Salamander/Visual_ROS#3]

**Comment by Setouchi-Salamander** [comment]
やった。
一応画面上部にだしてGUIを上下させればしきい値の変更ができるようになってる。
RGBのHIGH,LOWとグレースケールのHIGH,LOWをいじれるようにしてる。
いまは初期値を青にしてあるので青からスタートになってる。
ワンタッチで初期値が変えられたほうがいいか？

**Comment by okadatech** [comment]
launchで切り替えられるようにしておいて
launchのパラメータでやればいいよ。

**Comment by okadatech** [comment]
動作確認した
